#!/usr/bin/env python

import argparse
import sys


def main():

    parser = argparse.ArgumentParser(prog="civetqc")
    parser.add_argument("path_csv", help="path to csv file outputted by CIVET")
    args = parser.parse_args(sys.argv[1:])
    print(args)


if __name__ == "__main__":
    main()
